# AGRL130 week 3 solution inventory, 2026-09-21.
# Every solution is tied to a cited edge of its problem block (outputs/agrl130-graph/edges-lane*.csv).
# cls: SRC cut the source, PATH cut the path, RCPT cut the receptor's time or intake, DEC change the decision (rule, price, information, enforcement).
# gates: G1 reach (a student group can get to the user or site to pilot it), G2 semester (an effect can be produced and measured by December),
#        G3 additive (not already the standing rule or product in Abu Dhabi; V = passes pending a check), G4 no emirate-level law change needed to pilot.
# scores (only for solutions through all four gates), 1 to 5: User, Feasibility, Implementability, Usability, Market, Impact, Measurability, Time-to-effect.
# weights: Impact 3, Feasibility 2, Implementability 2, Measurability 2, User 1, Usability 1, Market 1, Time 1 (max 65).

PROBLEMS = {
 "P1": ("Construction workers and site neighbours", "Migrant construction workers on Abu Dhabi sites, and residents next to the fence, breathe site dust and diesel exhaust for a working day; the graph block holds the dust source, the fenceline and the two exposed groups. Out: vendors, road traffic, ambient dust storms.", 16.9),
 "P2": ("Street food vendors", "Vendors and helpers at charcoal and gas stalls stand in their own cooking smoke for a shift; the block is fuel, stall, concentration, vendor. Out: customers, restaurant kitchens, traffic.", None),
 "P3": ("School gate and idling", "Pupils, parents and staff in the arrival and dismissal zone breathe the queue's idling exhaust, which also seeps into gate-side classrooms; the block is car and bus idling, gate concentration, infiltration, classroom. Out: the commute itself, home, ambient dust.", 0.68),
 "P4": ("Child commute and daily dose", "A pupil's inhaled dose over the day, dominated by the bus or car commute and the home; the block is time-activity, in-vehicle air, breathing rate, peaks, lung and cognition outcomes. Out: what happens at the gate, the emission sources themselves.", 3.2),
 "P5": ("Near-road residents and delivery riders", "People who live within a few hundred metres of an arterial road, and riders who spend a shift on it, breathe the traffic increment on top of Abu Dhabi's ambient PM; the block is the near-road gradient, on-road concentration, the two exposed groups and their health outcomes. Out: schools, sites, stalls, regional dust.", 7.0),
}

S = []  # (problem, edge, cls, text, gates, scores)
def add(p, edge, cls, text, gates, scores=None):
    assert len(gates) == 4 and set(gates) <= set("YNV"), (p, text, gates)
    if all(g in "YV" for g in gates):
        assert scores is not None and len(scores) == 8, (p, text)
    else:
        scores = None
    S.append((p, edge, cls, text, gates, scores))

# ---------------- P1 construction workers and site neighbours (16 edges) ----------------
P="P1"
add(P,"A12->P16","SRC","Scheduled water misting of haul roads and active earthwork faces, frequency set by a site wind and humidity reading","VYYY",(3,4,3,3,3,4,4,4))
add(P,"A12->P16","SRC","Surfactant or polymer binder sprayed on unpaved site roads (Chang 2010: about 93 % control on unpaved roads)","YYYY",(3,4,3,4,3,4,4,4))
add(P,"A12->P16","SRC","Covered stockpiles with windbreak netting on the upwind side","YYVY",(2,5,4,4,3,3,3,5))
add(P,"A12->P16","SRC","Wheel-wash and rumble grid at the site exit so trucks do not carry mud onto public roads","VYVY",(2,4,3,4,3,2,3,4))
add(P,"A12->P16","SRC","Enclosed on-site crushing with water spray at the crusher (Bello 2019: below the PEL with the crusher's own spray, not with a water cannon)","NYVY")
add(P,"A12->P16","SRC","Wet cutting mandatory for concrete and block cutting, dry cutting banned on site (Middaugh 2012: 78 % cut)","VYVY",(4,4,3,3,3,4,4,5))
add(P,"A12->P16","SRC","Vacuum-shrouded saws and grinders with HEPA extraction for finishing trades","VYYY",(4,4,3,3,3,3,4,5))
add(P,"A12->P16","SRC","Pre-wetting of structures before demolition and during breaking","NYVY")
add(P,"A12->P16","SRC","Paving or gravelling the main haul road in the first month of the project instead of the last","NYYY")
add(P,"A12->P16","SRC","15 km/h site speed limit with a speed bump at the gate, which cuts road-dust lift","VYYY",(2,5,4,4,4,2,3,5))
add(P,"A12->S30","PATH","Perimeter dust fence whose height is set per wind direction by CFD (Choi 2023)","NYYY")
add(P,"A12->S30","PATH","Fenceline PM10 sensors that trigger the perimeter misting line automatically above a threshold","YYYY",(3,4,3,4,4,4,5,4))
add(P,"A12->S30","PATH","Fog cannon at the fenceline aimed at the downwind boundary during dusty operations","YYYY",(3,4,3,3,3,3,4,4))
add(P,"A12->S30","PATH","Dense hedge or vegetation screen along the fence facing homes","YNYY")
add(P,"A12->S30","PATH","Site layout that puts crushing, mixing and stockpiles at the point furthest from the neighbours' fence","NYYY")
add(P,"A12->X14","RCPT","FFP2 or N95 provision with fit testing for every worker in a dust trade, replaced on a schedule","VYVY",(3,5,3,2,3,3,3,5))
add(P,"A12->X14","RCPT","Powered air-purifying respirators for cutters, chippers and grinders (Bello 2019: chipping stayed above the PEL even with N95)","VYYY",(4,4,3,2,2,3,3,5))
add(P,"A12->X14","RCPT","Rotation cap on high-dust tasks: no worker more than 2 h a shift on cutting or breaking","VYYY",(4,4,3,3,3,3,3,5))
add(P,"A12->X14","RCPT","Filtered, pressurised cabs for excavator and loader operators (Azarmi 2016: cabin dose 57x background for coarse particles)","NYYY")
add(P,"A12->X14","RCPT","Dust-task scheduling to low-wind hours from the day's forecast","VYYY",(3,4,3,3,3,3,4,5))
add(P,"A12->X14","RCPT","Personal real-time dust badge with a vibrating alert at a set PM2.5 level (Kim 2025: alerts within 20 m)","YYYY",(4,4,3,3,3,3,5,4))
add(P,"A12->X17","PATH","Flexible-height barrier panels raised on the downwind side of the day (Choi 2023: resident exposure varies 2.3x with wind direction)","NYYY")
add(P,"A12->X17","DEC","SMS to registered neighbours before crushing or demolition hours, advising closed windows","YYYY",(4,5,4,3,2,2,4,5))
add(P,"A12->X17","DEC","Demolition and crushing restricted to hours when neighbouring homes are emptiest","NYVY")
add(P,"A24->S30","PATH","Wind-vane-triggered misting that runs only on the downwind boundary","YYYY",(3,4,3,4,4,4,5,4))
add(P,"A24->S30","DEC","Dust-operation permit tied to the forecast: no crushing, sweeping or demolition on high-wind days","NYVY")
add(P,"A24->X17","PATH","Portable fog cannon repositioned daily to the neighbour side downwind","YYYY",(3,4,3,3,3,3,4,4))
add(P,"D09->D18","SRC","Covered skips and on-site waste separation so demolition fines do not sit in open piles","VYVY",(2,5,4,4,3,2,3,5))
add(P,"D09->D18","SRC","Recycled aggregate specified in the contract to cut quarry haulage and crushing on site","NYYY")
add(P,"D09->X14","SRC","Silica-free abrasive and low-silica block specified for the trades that generate the finest dust","NYYY")
add(P,"D09->X14","SRC","Off-site prefabrication of cut elements so cutting happens under extraction, not in the open","NYYY")
add(P,"D16->E18","RCPT","Midday break window aligned with the dustiest tasks so heat and dust peaks are not stacked on the same hours","VYVY",(4,4,3,3,3,3,3,5))
add(P,"D16->E18","RCPT","Shaded rest areas with a filtered-air cabin on site","VYYY",(5,4,3,4,3,3,4,4))
add(P,"D16->E18","RCPT","WBGT-triggered work stops with a site display of the reading","VYVY",(4,4,3,4,3,2,4,5))
add(P,"D16->X14","RCPT","Hydration and heart-rate wearables that flag workers in the danger zone (Moohialdin 2022)","VYYY",(4,3,3,3,3,2,4,4))
add(P,"P16->S30","DEC","Continuous perimeter PM10 monitor with a public dashboard for the site","YYYY",(3,5,4,4,3,3,5,5))
add(P,"P16->S30","SRC","Truck sheeting enforced at the gate: no uncovered load leaves the site","VYVY",(2,5,4,4,3,2,3,5))
add(P,"S16->X14","RCPT","Humidity-aware scheduling: on the most humid mornings the heaviest tasks move to the afternoon window","VYYY",(3,4,3,3,3,2,3,5))
add(P,"S30->X14","RCPT","Site-wide dust alert on the PA or phones when any perimeter node crosses the threshold","VYYY",(3,5,4,4,3,3,5,5))
add(P,"S30->X14","RCPT","Marked dust exclusion zones that clear non-essential workers during crushing or sweeping peaks","VYYY",(3,4,3,3,3,3,3,5))
add(P,"S30->X17","RCPT","Contractor-funded air purifiers for the homes on the fence side for the duration of the works","YYYY",(5,4,3,4,2,3,4,5))
add(P,"S30->X17","DEC","Neighbour dashboard and complaint line fed by the perimeter monitors","YYYY",(4,5,4,4,2,2,5,5))
add(P,"S30->X17","PATH","Planning setback between the site fence and the nearest homes for future sites","NNNY")
add(P,"X14->E18","RCPT","Baseline and periodic spirometry for workers in high-dust trades","YYVY",(4,4,3,3,2,2,5,4))
add(P,"X14->E19","RCPT","Silicosis surveillance register for cutters, chippers and crushers","NYVY")
add(P,"X14->E18","RCPT","Smoking cessation programme on site, since smoking multiplies dust harm","YYYY",(3,4,3,3,2,2,3,3))
add(P,"X14->E19","DEC","Medical surveillance requirement written into the visa medical for dust trades","NNNN")
add(P,"X14->E18","DEC","Dust and silica training in the workers' own languages, with a short film for the site induction","YYYY",(4,5,4,4,3,2,3,5))
add(P,"A12->S30","DEC","Contractor dust-performance bond released against fenceline readings","NNVY")
add(P,"A12->P16","DEC","Tender scoring that awards points for a measured dust plan","NNVY")
add(P,"P16->S30","DEC","Public league table of sites by fenceline PM10","YYYY",(3,4,3,4,2,3,5,4))
add(P,"A24->S30","DEC","Drone dust patrol by the municipality over active sites on windy days","NNVY")
add(P,"A12->P16","DEC","Reduced permit fees for sites that run continuous monitoring","NNVY")
add(P,"S30->X14","DEC","Worker hotline for dust violations in three languages","YYYY",(4,5,4,3,2,2,3,5))
add(P,"A12->S30","DEC","Dust records linked to the contractor's insurance premium","NNVY")
add(P,"S30->X17","DEC","Resident app to report dust clouds with a geotagged photo, routed to the site and the municipality","YYYY",(4,4,3,4,2,2,4,4))
add(P,"A12->X14","DEC","Dust-control competency certificate required for site supervisors","NNVY")
add(P,"P16->S30","DEC","Site dust score printed as a QR on the hoarding, updated daily from the monitors","YYYY",(3,5,4,4,3,2,4,5))
add(P,"D09->X14","DEC","Hoarding-side realtime display of PM10 so passers-by and workers see the number","YYYY",(3,5,4,4,3,2,4,5))
add(P,"A12->X14","RCPT","Shift-end shower and clothes-change facility so dust does not travel home","VYVY",(4,4,3,4,2,2,2,4))

# ---------------- P2 street vendors (7 edges) ----------------
P="P2"
add(P,"A23->P31","SRC","LPG conversion of charcoal grills at licensed stalls, with a rebate on the licence fee","VYVY",(4,4,3,4,4,5,5,4))
add(P,"A23->P31","SRC","Induction or electric grill at stalls with a power hookup","VYYY",(4,4,3,4,3,5,5,4))
add(P,"A23->P31","SRC","Low-smoke charcoal briquettes or coconut-shell charcoal in place of lump charcoal","YYYY",(4,5,4,5,4,3,4,5))
add(P,"A23->P31","SRC","Chimney starter for lighting charcoal, no lighter fluid","YYYY",(4,5,4,5,4,2,4,5))
add(P,"A23->P31","SRC","Power hookups installed at fixed vending spots so electric cooking is possible","NYYY")
add(P,"A23->P31","SRC","Pellet grill or gas griddle for items now cooked over charcoal","VYYY",(3,4,3,4,3,4,5,4))
add(P,"A23->P31","SRC","Solar-battery cart powering an induction plate at outdoor markets","YYYY",(3,3,3,3,3,4,5,3))
add(P,"A23->S29","PATH","Canopy hood over the grill with a fan and grease filter, exhaust above head height","YYYY",(4,4,3,3,4,4,5,4))
add(P,"A23->S29","PATH","Extraction hood with an electrostatic precipitator on the exhaust","YYYY",(3,3,3,3,3,4,5,3))
add(P,"A23->S29","PATH","Water-scrubber hood for charcoal exhaust","YYYY",(3,3,2,3,3,4,5,3))
add(P,"A23->S29","PATH","Exhaust stack that discharges 3 m above the stall roof","YYYY",(3,4,3,4,3,3,5,4))
add(P,"A23->S29","PATH","Stall orientation rule: grill on the leeward edge, vendor upwind","YYYY",(3,5,4,3,4,3,4,5))
add(P,"A23->S29","PATH","Shared ventilated cooking kiosk at a market, several vendors under one hood","NYYY")
add(P,"A23->S29","PATH","Wind wall or screen between the grill and the vendor's station","YYYY",(3,5,4,3,4,2,4,5))
add(P,"A23->X16","RCPT","Vendor station moved to the upwind side of the grill, serving from the front","YYYY",(4,5,4,3,4,3,4,5))
add(P,"A23->X16","RCPT","Rotation between grilling and serving so no one stands at the grill a full shift","YYYY",(3,5,4,3,4,3,3,5))
add(P,"A23->X16","RCPT","FFP2 mask during charcoal lighting and fanning, the highest-peak minutes","YYYY",(3,5,4,2,4,2,3,5))
add(P,"A23->X16","RCPT","Helper handles charcoal lighting and ash while wearing a respirator","YYYY",(3,5,4,3,4,2,3,5))
add(P,"A23->X16","RCPT","Shorter charcoal shifts with a break away from the stall each hour","YYYY",(3,4,3,3,3,2,3,5))
add(P,"D24->P31","DEC","Clean fuel as a condition of vending licence renewal","NNVY")
add(P,"D24->P31","DEC","Vendors clustered in ventilated food courts or designated zones away from traffic","NNYY")
add(P,"D24->P31","DEC","Cap on charcoal stalls per street or market","NNVY")
add(P,"D24->P31","DEC","Charcoal lighting restricted to set hours before the crowd arrives","YYYY",(3,5,4,3,4,2,4,5))
add(P,"D24->P31","DEC","Minimum spacing between grills at a market so plumes do not stack","YYYY",(3,5,4,4,4,2,4,5))
add(P,"P31->S29","SRC","Grill with controlled airflow and a lid so combustion is cleaner and fumes are trapped","YYYY",(3,4,3,4,4,3,5,4))
add(P,"P31->S29","SRC","Catalytic afterburner on the grill exhaust","YYYY",(2,3,2,3,2,3,5,3))
add(P,"P31->S29","SRC","Lid-on cooking for items that allow it, cutting open-flame time","YYYY",(3,5,4,4,4,2,4,5))
add(P,"P31->S29","SRC","Pre-cooked items finished on the grill briefly, cutting minutes over charcoal","YYYY",(3,5,4,4,4,2,4,5))
add(P,"S29->X16","RCPT","Personal PM monitor clipped at the stall with a visible alert","YYYY",(3,5,4,4,3,2,5,5))
add(P,"S29->X16","PATH","Fan-based dilution blowing across the grill away from the vendor","YYYY",(3,5,4,4,4,3,4,5))
add(P,"S29->X16","PATH","Stall layout with the grill at the edge and the vendor inside a partly enclosed counter","YYYY",(3,4,3,3,4,3,4,4))
add(P,"S29->X16","RCPT","Customer queue positioned upwind of the grill so the crowd is not in the plume","YYYY",(3,5,4,4,4,1,3,5))
add(P,"X16->E18","RCPT","Respiratory symptom screening at licence renewal with referral","NYVY")
add(P,"X16->E18","RCPT","Vendor health survey and free lung-function check at a market","YYYY",(4,4,3,4,2,2,5,4))
add(P,"X16->E18","DEC","Training session for vendors on smoke exposure and the cheap fixes","YYYY",(4,5,4,4,3,2,3,5))
add(P,"X16->E18","RCPT","CO alarm at charcoal stalls in semi-enclosed spots","YYYY",(4,5,4,4,4,2,4,5))
add(P,"A23->P31","DEC","Clean-stall label displayed to customers, awarded after a measurement","YYYY",(4,4,3,4,4,3,5,4))
add(P,"A23->S29","DEC","Municipality rebate for hood installation at licensed stalls","NNVY")
add(P,"A23->P31","DEC","Vendor cooperative bulk-buying LPG and cylinders","VYYY",(3,4,3,4,4,4,4,4))
add(P,"S29->X16","DEC","Air-quality display facing customers at the stall","YYYY",(3,5,4,4,3,2,5,5))
add(P,"A23->P31","DEC","Event-organiser rule: electric hookups and no charcoal at organised markets and festivals","VYVY",(3,4,3,4,4,4,5,4))
add(P,"A23->S29","DEC","Hood retrofit built and installed by the engineering student group at one market as the pilot","YYYY",(4,4,3,3,3,4,5,4))
add(P,"A23->S29","DEC","Filter-cleaning subscription so hoods keep working after installation","YYYY",(3,4,3,4,4,3,3,4))
add(P,"P31->S29","DEC","Measurement campaign ranking stall types by PM2.5 so the worst are fixed first","YYYY",(3,5,4,5,3,3,5,5))
add(P,"D24->P31","DEC","Trained smoke marshal at markets who checks fuel, hoods and spacing","YYYY",(3,4,3,4,3,2,3,5))
add(P,"A23->P31","DEC","Clean cooking zone pilot at one market with LPG and hoods for every stall","VYYY",(4,4,3,4,4,5,5,4))
add(P,"A23->X16","RCPT","Nose-and-mouth shield at the grill face for the minutes of flare-up","YYYY",(2,5,4,2,3,1,3,5))
add(P,"A23->S29","PATH","Enclosed food truck with roof extraction and filter instead of an open stall","NYYY")
add(P,"D24->P31","DEC","Vendor spacing and orientation drawn into the market floor plan","YYYY",(3,5,4,4,4,2,4,5))
add(P,"S29->X16","RCPT","Two-station stall: hot station for 20 minutes, cold station for 20, alternating","YYYY",(3,5,4,3,4,3,3,5))

# ---------------- P3 school gate and idling (25 edges) ----------------
P="P3"
add(P,"A05->P05","DEC","School idle-free policy with signage at the gate and in the parent handbook","YYYY",(4,5,4,4,3,3,4,5))
add(P,"A05->P05","DEC","Engine-off pledge signed by parents and drivers at the start of term","YYYY",(4,5,4,4,3,2,4,5))
add(P,"A05->S20","DEC","Staff-enforced engine-off in the queue with a verbal reminder at the window (Ryan 2013: 4.11 to 0.99 ug/m3 at the most-bused school)","YYYY",(4,5,4,3,3,4,5,5))
add(P,"A05->S20","DEC","Student idle marshals with tally sheets at the gate","YYYY",(4,5,4,3,2,3,5,5))
add(P,"A05->P05","DEC","Camera plus plate reading that sends a letter home to idling families","VYVY",(2,3,2,4,2,3,5,3))
add(P,"A05->P05","DEC","Idle-free zone painted on the road surface at the drop-off","YYYY",(3,5,4,5,3,2,4,5))
add(P,"A05->P05","DEC","Municipal anti-idling rule for school zones with an air-quality rationale (Abu Dhabi Police's Dh300 covers unattended engines only)","NNYN")
add(P,"A05->S07","DEC","Countdown display at the gate showing minutes since arrival, engine-off asked at one minute","YYYY",(3,4,3,4,3,3,5,5))
add(P,"A05->P05","DEC","Engine-off training for hired family drivers, who do most Abu Dhabi school runs","YYYY",(4,5,4,4,3,4,4,5))
add(P,"A05->S08","DEC","Bus operator contract clause: no idling over one minute at the gate, checked by telematics","VYYY",(4,4,3,4,3,4,5,4))
add(P,"A07->D14","PATH","School Street: the gate road closed to cars at drop-off and pick-up (Mayor of London 2021: NO2 down up to 23 %)","VYYY",(4,3,2,3,3,5,5,4))
add(P,"A07->D14","PATH","Park-and-stride: drop-off point 300 m away with a marshalled walking route","YYYY",(3,4,3,3,3,4,5,5))
add(P,"A07->S20","PATH","Staggered drop-off and pick-up by grade to shorten the queue","YYYY",(4,5,4,4,3,4,5,5))
add(P,"A07->S20","PATH","One-way rolling drop-off loop, no stopping, staff open the doors","YYYY",(4,4,3,4,3,4,5,5))
add(P,"A07->S20","PATH","Drop-off bays relocated away from the pedestrian gate","VYYY",(3,4,3,4,3,4,5,4))
add(P,"A07->S20","PATH","Kiss-and-ride lane with attendants so cars keep moving","YYYY",(4,4,3,4,3,4,5,5))
add(P,"A07->S20","PATH","Pedestrian entrance moved to the side away from the queue","NYYY")
add(P,"A07->S20","RCPT","Shaded, cooled parent waiting area so parents do not wait in cars with the AC on","YYYY",(5,4,3,4,3,4,5,4))
add(P,"A07->S20","PATH","Covered walkway from the drop-off bay to the door","VYYY",(3,4,3,4,3,2,3,4))
add(P,"A07->S20","PATH","Hedge or tree screen between the queue lane and the gate","YNYY")
add(P,"A07->D14","DEC","Just-in-time pick-up app: parents are called when the child reaches the gate, so nobody queues with the engine on (car half only; rescored 04:10 after the pre-mortem: relocates the wait, dismissal only, gate effect under sensor noise, exists as iSchoolRide PickupLine)","YYYY",(5,4,3,4,4,2,2,4))
add(P,"A07->D14","DEC","Numbered pick-up tags and a call board, the low-tech version of the app (car half only, rescored 04:10 with the app)","YYYY",(4,5,4,4,3,2,2,5))
add(P,"A07->D14","PATH","Remote pick-up points at a nearby car park with staff walking the children over","YYYY",(3,4,3,3,3,4,5,5))
add(P,"A07->D14","PATH","Walking bus with adult marshals from a collection point","YYYY",(3,4,3,3,2,3,4,5))
add(P,"A15->S21","RCPT","Portable HEPA cleaners in classrooms (Simona 2025: PM2.5 39.9 % lower over the year)","YYYY",(5,5,4,5,3,4,5,5))
add(P,"A15->X10","RCPT","MERV13 filter upgrade on the school's air handling units","YYYY",(4,4,3,5,3,4,5,4))
add(P,"A15->X10","RCPT","Positive pressure in gate-side classrooms with filtered supply air","VYYY",(4,3,2,5,3,4,5,3))
add(P,"A15->S21","PATH","Sealing window and door gaps on the gate-facing façade","YYYY",(3,5,4,5,3,3,4,5))
add(P,"A15->S21","RCPT","Purifiers only in the gate-facing classrooms, the cheapest targeting","YYYY",(4,5,4,5,4,3,5,5))
add(P,"A15->X10","RCPT","Filter change schedule driven by a classroom PM sensor","YYYY",(3,5,4,4,3,3,5,5))
add(P,"A18->X10","DEC","Siting rule for new schools: at least 300 m from an arterial","NNVN")
add(P,"A18->X10","DEC","Gate placement rule away from the arterial for new schools","NNVN")
add(P,"A18->X10","RCPT","Room allocation: the youngest classes furthest from the gate and the road","YYYY",(4,5,4,5,3,3,4,5))
add(P,"A26->D26","SRC","Automatic idle shut-off timers on school buses","VYYY",(3,4,3,5,3,4,5,4))
add(P,"A26->P32","SRC","Electric school buses on the routes serving the school","NYVY")
add(P,"A26->D26","SRC","Shore power at the depot and the staging area so bus AC runs without the engine","NYYY")
add(P,"D26->P05","PATH","Bus staging area away from the gate, engines off until loading","YYYY",(3,5,4,4,3,4,5,5))
add(P,"D26->P05","PATH","Bus arrival slots so buses load on arrival instead of waiting","YYYY",(3,4,3,4,3,3,5,5))
add(P,"A26->P32","SRC","Diesel oxidation catalyst or DPF retrofit on older buses","NYVY")
add(P,"D26->P32","DEC","Telematics idle report per bus with a league table for the operator","VYYY",(3,4,3,4,3,3,5,4))
add(P,"D26->P32","DEC","Driver bonus for the lowest idle hours","VYYY",(3,4,3,4,4,3,5,4))
add(P,"A26->P32","SRC","CNG buses on school contracts","NNVY")
add(P,"A27->X10","RCPT","Demand-controlled ventilation with CO2 and PM sensors (Arar 2021: ventilation beat purifiers in UAE nurseries)","VYYY",(4,3,2,5,3,4,5,3))
add(P,"A27->X10","RCPT","Outdoor-air intake reduced during the drop-off peak, restored after","YYYY",(3,4,3,5,3,3,5,4))
add(P,"A27->X10","PATH","Air intake relocated away from the gate and the road","NYYY")
add(P,"A27->X10","RCPT","Energy recovery ventilator with filtration for the gate-side wing","NYYY")
add(P,"D04->D14","DEC","School bus fee discount funded by a car drop-off fee","VYVY",(3,4,3,4,4,4,4,4))
add(P,"D04->D14","DEC","Carpool matching for families on the same streets","YYYY",(3,5,4,3,3,3,4,5))
add(P,"D15->D14","DEC","Enrolment preference for families within walking distance","NNVY")
add(P,"D04->D14","PATH","Bike and e-scooter parking with a safe entry lane","YYYY",(3,5,4,4,3,2,4,5))
add(P,"D15->D14","DEC","Public bus route stop at the school gate at the school's hours","NYVY")
add(P,"D14->P05","PATH","Staff load and unload children so the queue rolls (Kumar 2020: drop-off PM2.5 nearly 3x off-peak from queuing)","YYYY",(4,5,4,4,3,4,5,5))
add(P,"D14->P05","DEC","No-parking, roll-through rule with cones and a marshal","YYYY",(3,5,4,4,3,3,5,5))
add(P,"D14->P05","DEC","Parent briefing on engine-off in the queue at the term's first assembly","YYYY",(4,5,4,4,3,3,4,5))
add(P,"D14->P05","DEC","Signage that states the fuel and dirhams saved by switching off","YYYY",(3,5,4,4,3,2,4,5))
add(P,"P05->S20","PATH","Physical distance: the queue lane moved 30 m from the pedestrian gate","VYYY",(3,4,3,4,3,4,5,4))
add(P,"P05->S20","PATH","Enclosed, ventilated gate vestibule where children wait","NYYY")
add(P,"P05->S20","PATH","Green wall at the gate as a partial screen (Kumar 2024: hedges about 23 %)","YNYY")
add(P,"S13->S20","DEC","Stable-morning alert: on inversion days the queue is shortened by a later staggered slot","YYYY",(3,4,3,3,3,2,4,5))
add(P,"S13->S20","RCPT","Dust and inversion day protocol: children wait indoors at pick-up","YYYY",(4,5,4,4,3,2,4,5))
add(P,"S20->S21","RCPT","Windows closed during drop-off and pick-up in gate-side rooms","YYYY",(3,5,4,4,3,3,5,5))
add(P,"S20->X10","RCPT","Gate-side doors kept shut during the peak, entry through the far door","YYYY",(3,5,4,4,3,3,4,5))
add(P,"S20->X10","PATH","Air curtain at the main entrance","VYYY",(3,4,3,5,3,2,4,4))
add(P,"S26->X10","SRC","No chalk, wet cleaning and HEPA vacuums after hours (Arar 2021: TSP moved with children's activity)","YYYY",(3,5,4,4,3,3,4,5))
add(P,"S26->X10","SRC","Entrance mats and a shoe-off rule in the youngest classes","YYYY",(3,5,4,3,3,2,4,5))
add(P,"S26->X10","SRC","No incense or air fresheners in classrooms","YYYY",(3,5,4,4,3,2,4,5))
add(P,"S07->E14","DEC","Black-carbon co-benefit reported in the school's sustainability report","YYYY",(2,5,4,5,2,1,3,5))
add(P,"S08->X10","RCPT","Youngest pupils kept away from the tail of the queue at pick-up","YYYY",(3,5,4,4,3,2,4,5))
add(P,"P05->S20","DEC","Real-time PM display at the gate visible to every parent in the queue","YYYY",(4,5,4,4,3,3,5,5))
add(P,"P05->S20","DEC","Weekly gate air-quality report to parents","YYYY",(3,5,4,4,3,2,5,5))
add(P,"A05->S20","DEC","ADEK guideline for school-gate air, drafted from the pilot's data","NNYY")
add(P,"A05->S20","DEC","Air quality as a criterion in the school inspection framework","NNYN")
add(P,"P05->S20","DEC","Student measurement project with low-cost sensors feeding the gate display","YYYY",(4,5,4,4,2,3,5,5))
add(P,"A05->P05","DEC","Class competition on engine-off rates counted by the marshals","YYYY",(4,5,4,4,2,3,5,5))
add(P,"D14->P05","DEC","Peak-hour parking enforcement on the gate road by the municipality","NYVY")
add(P,"D04->D14","DEC","Fee rebate for families who use the bus all year","VYVY",(3,4,3,4,4,3,4,4))
add(P,"D04->D14","DEC","Clean-commute badge for families who walk, bus or carpool","YYYY",(3,5,4,4,2,2,4,5))
add(P,"S20->S21","RCPT","Corridor doors kept shut on the gate side to keep the peak out of the wing","YYYY",(3,5,4,4,3,2,4,5))
add(P,"A26->D26","SRC","Bus AC pre-cooled on shore power before departure so the wait at the gate is engine-off","NYYY")
add(P,"A07->S20","PATH","Queue lane on the downwind side of the gate on the prevailing wind","VYYY",(3,4,3,4,3,3,4,4))
add(P,"D26->P05","DEC","Gate orchestration system: buses get arrival slots and an engine-off staging bay, cars get the just-in-time call, one dashboard at the door (rescored 04:10 after the pre-mortem: engine-off is not available in the heat, the wait relocates, the gate effect is under sensor noise)","VYYY",(5,2,3,4,4,3,2,4))

# ---------------- P4 child commute and daily dose (29 edges) ----------------
P="P4"
add(P,"A04->A20","DEC","Bus-first policy: bus fee cut and a car drop-off fee","VYVY",(3,4,3,4,4,4,4,4))
add(P,"A04->A20","DEC","Electric buses required in the next school transport tender","NNVY")
add(P,"A04->X08","PATH","Route optimisation to cut time on board for the youngest pupils","VYYY",(4,4,3,4,4,3,5,4))
add(P,"A04->X08","PATH","Bus stops sited off the arterial and away from queues","VYYY",(3,4,3,4,3,2,4,4))
add(P,"A04->X08","RCPT","Windows-closed and recirculation policy on buses in traffic (Matthaios 2020: lowest I/O with recirculation)","YYYY",(3,5,4,4,3,3,5,5))
add(P,"A04->X08","RCPT","HEPA-grade cabin filters on the school buses","VYYY",(4,4,3,5,3,4,5,4))
add(P,"A04->X08","DEC","Cabin PM monitor on each bus with driver feedback","YYYY",(3,4,3,4,3,3,5,5))
add(P,"A13->X03","DEC","Dust-day alert to schools with an indoor-recess protocol (MOCCAE 2022 lists the missing public warning system as a gap)","YYYY",(4,5,4,4,3,3,4,5))
add(P,"A13->X03","DEC","NCM dust forecast pushed into the school app","VYYY",(4,4,3,4,3,3,4,4))
add(P,"A13->X11","DEC","Asthma-register pupils get a personal alert on dust and peak days","YYYY",(5,4,3,4,3,3,4,5))
add(P,"A13->X03","DEC","Outdoor PE timetable set by the forecast","YYYY",(4,5,4,4,3,3,4,5))
add(P,"A14->X03","DEC","School-level air-quality display in the lobby","YYYY",(3,5,4,4,3,2,5,5))
add(P,"A14->X03","DEC","Parent app showing commute air quality by route","VYYY",(3,4,3,4,3,2,4,4))
add(P,"A14->X03","DEC","Route advice: walking routes on quieter streets, away from the queue","YYYY",(3,5,4,3,2,2,4,5))
add(P,"A17->X11","RCPT","School nurse asthma action plans for every registered pupil","YYYY",(5,5,4,4,2,2,4,5))
add(P,"A17->X11","RCPT","Inhaler-at-school programme","YYYY",(5,5,4,4,2,2,3,5))
add(P,"A17->X11","RCPT","Spirometry screening for the highest-exposure pupils","YYYY",(4,4,3,3,2,2,5,4))
add(P,"A20->E05","SRC","DPF or DOC retrofit on the oldest buses (Adar 2015: on-board particles 10 to 50 % lower with cleaner tech)","NYVY")
add(P,"A20->S22","SRC","Closed crankcase ventilation retrofit, the cheapest cabin fix","VYVY",(3,4,3,5,3,4,5,4))
add(P,"A20->S22","SRC","Bus age cap in the school's transport contract","NNVY")
add(P,"A20->X19","SRC","Electric buses on the longest routes first","NYVY")
add(P,"A20->X19","RCPT","Positive-pressure filtered cabin on the buses","NYYY")
add(P,"A20->X19","RCPT","Seating plan: youngest at the front, away from the engine and exhaust","YYYY",(3,5,4,4,3,2,4,5))
add(P,"A20->S22","SRC","Exhaust-leak inspection of every bus at the start of term","YYYY",(4,5,4,5,3,3,5,5))
add(P,"A20->S22","SRC","Idle timers on buses so cabin fumes do not build while waiting","VYYY",(3,4,3,5,3,3,5,4))
add(P,"P30->X09","SRC","Bakhoor and oud burning guidance: outdoors or with the window open, never in the child's room (Cohen 2013)","YYYY",(3,5,4,3,3,3,4,5))
add(P,"P30->X09","SRC","Electric bakhoor burners that produce less smoke","YYYY",(3,5,4,4,4,2,4,5))
add(P,"P30->X09","SRC","Kitchen extraction hood used every time the stove is on","YYYY",(3,5,4,3,3,2,4,5))
add(P,"P30->E06","SRC","No shisha or smoking indoors where children sleep","YYYY",(4,5,4,3,2,3,4,5))
add(P,"P30->X09","RCPT","Air purifier in the child's bedroom","YYYY",(4,5,4,5,4,3,5,5))
add(P,"P30->X13","SRC","Incense only after the children are out of the room, with ventilation after","YYYY",(3,5,4,3,3,2,4,5))
add(P,"P30->X09","DEC","Home air-quality information pack sent through the school","YYYY",(3,5,4,4,3,2,3,5))
add(P,"S22->X08","RCPT","Car: recirculation and closed windows in traffic, a one-line parent instruction","YYYY",(4,5,4,4,3,3,5,5))
add(P,"S22->X08","RCPT","HEPA cabin filter in the family car","YYYY",(4,5,4,5,4,3,5,5))
add(P,"S22->X08","RCPT","Driver training: do not follow diesel vehicles closely in the queue","YYYY",(3,5,4,3,3,2,4,5))
add(P,"S22->X08","PATH","Route choice via quieter roads for the school run","YYYY",(3,5,4,3,3,2,4,5))
add(P,"S22->X06","RCPT","Commute shortened by staggered school timings that avoid the road peak","VYYY",(4,4,3,4,3,3,4,4))
add(P,"X03->X05","RCPT","No strenuous sport at road-peak hours or on dust days","YYYY",(4,5,4,4,3,3,4,5))
add(P,"X03->X05","RCPT","Indoor sports hall use on dust days","YYYY",(4,5,4,4,3,2,4,5))
add(P,"X03->X08","RCPT","Shaded, cooled waiting pods at bus stops","NYYY")
add(P,"X03->X08","RCPT","Bus tracking app so children wait indoors until the bus is two minutes away","YYYY",(5,4,3,4,4,3,4,4))
add(P,"X04->X06","RCPT","Just-in-time pick-up app to cut gate waiting time (rescored 04:10 with P3-21)","YYYY",(5,4,3,4,4,2,3,4))
add(P,"X04->X06","RCPT","Gate waiting moved indoors","YYYY",(4,5,4,4,3,3,5,5))
add(P,"X04->X13","RCPT","Bus staging inside the campus, away from the road","VYYY",(3,4,3,4,3,3,5,4))
add(P,"X04->X13","PATH","Walking routes that avoid the car queue","YYYY",(3,5,4,3,2,2,4,5))
add(P,"X05->X06","RCPT","PE moved to midday indoors rather than morning outdoors beside the road","YYYY",(3,5,4,4,3,2,4,5))
add(P,"X05->X06","RCPT","Running events held at the field furthest from the road","YYYY",(3,5,4,4,3,2,3,5))
add(P,"X06->E05","RCPT","Lung-function cohort at the school, measured each term","YYYY",(4,4,3,3,2,2,5,4))
add(P,"X06->E06","RCPT","School health screening with an air-exposure questionnaire","YYYY",(3,5,4,4,2,2,4,5))
add(P,"X08->X13","RCPT","Peak-avoidance: walkers routed away from the queue tail","YYYY",(3,5,4,3,2,2,4,5))
add(P,"X13->X06","DEC","Personal monitors worn for a week to find each pupil's peaks","YYYY",(4,4,3,3,2,3,5,5))
add(P,"X13->X06","RCPT","Commute shifted by 20 minutes off the road peak","YYYY",(3,5,4,3,3,3,4,5))
add(P,"X09->X06","RCPT","Home ventilation guidance by week type (Yuan 2020: sealed homes in dust weeks)","YYYY",(3,5,4,3,3,3,4,5))
add(P,"X09->X06","RCPT","Window-sealing kits for road-facing bedrooms","YYYY",(3,5,4,4,3,2,4,5))
add(P,"X09->X06","RCPT","MERV13 filter on the home AC","YYYY",(4,5,4,5,4,3,5,5))
add(P,"X09->X06","DEC","Purifier subsidy for asthmatic pupils' homes","VYYY",(5,4,3,5,3,3,5,4))
add(P,"X19->X06","DEC","Cabin air-quality clause in the school bus contract","VYYY",(3,4,3,4,3,4,5,4))
add(P,"X19->X06","DEC","Driver engine-off training and a no-idling rule while loading","YYYY",(3,5,4,4,3,3,5,5))
add(P,"X19->X06","PATH","Loading order: the pupils with the longest ride board last","YYYY",(3,5,4,3,3,2,4,5))
add(P,"X19->E06","PATH","Direct routes for the youngest pupils","VYYY",(4,4,3,4,3,3,4,4))
add(P,"X19->X06","DEC","Regulator bus air-quality standard","NNYN")
add(P,"S22->X19","DEC","Parent campaign on car cabin settings, one page","YYYY",(3,5,4,4,3,2,3,5))
add(P,"X08->X13","DEC","School clean-commute scorecard published each term","YYYY",(3,5,4,4,2,2,4,5))
add(P,"S22->X08","DEC","School bulk-buys HEPA cabin filters for families at cost","YYYY",(4,5,4,5,4,3,5,5))
add(P,"X04->X06","DEC","Student sensor project mapping commute exposure by mode","YYYY",(4,5,4,4,2,3,5,5))
add(P,"A04->X08","DEC","Bus routes redesigned on exposure, not distance alone","VYYY",(3,3,2,4,3,3,4,3))
add(P,"A20->X19","DEC","Bus age legislation","NNVN")
add(P,"A04->A20","DEC","Walking and cycling infrastructure around the school","NNYY")
add(P,"X03->X06","RCPT","Time-outdoors budget on dust days in the school timetable","YYYY",(3,5,4,4,3,2,4,5))
add(P,"X13->X06","RCPT","Bus stop waiting indoors when the stop is on an arterial","YYYY",(4,5,4,4,3,2,4,5))
add(P,"S22->X19","SRC","Clean Cabin: per-bus cabin air diagnosis (cabin vs roof sensor ratio while idling and moving), fix kit (exhaust-leak sealing, closed-crankcase retrofit, tailpipe routed up and off-side away from the door and the intake), climate-aware idle timer, and a published cabin air rating per bus (added 04:10 after the pre-mortem, replaces gate orchestration as the pick)","VYYY",(5,4,3,5,4,5,5,5))

# ---------------- P5 near-road residents and delivery riders (42 edges) ----------------
P="P5"
add(P,"A16->S18","PATH","Dense roadside hedge 1.5 to 2 m between the road and the homes (Kumar 2024: hedges about 23 %)","YNYY")
add(P,"A16->S18","PATH","Street trees where the street is open, not in canyons where they trap","NNYY")
add(P,"A16->X18","PATH","Green wall on the road-facing façade of labour housing","YNYY")
add(P,"A16->X18","PATH","Vegetation barrier at the boundary of a road-facing compound","YNYY")
add(P,"A22->X15","RCPT","Surgical or FFP2 masks supplied by the platform (Patel 2016: only surgical masks cut PM for motorcycle commuters)","YYYY",(3,5,4,2,3,4,4,5))
add(P,"A22->X15","RCPT","Shift scheduling that keeps riders off the road at the traffic peaks","VYYY",(3,4,3,3,3,4,4,4))
add(P,"A22->X15","PATH","Route choice through lower-traffic roads coded into the dispatch app","VYYY",(3,4,3,4,3,3,4,4))
add(P,"A22->X15","RCPT","Filtered-air rest stops (the 12,000 summer rest areas exist for heat, not air, Gulf News 2026)","VYVY",(4,4,3,4,3,2,3,4))
add(P,"A22->X15","DEC","Exposure-based break entitlement written into rider contracts","NNVY")
add(P,"A22->X15","RCPT","Helmet with a filtered visor intake","YYYY",(2,3,3,2,3,2,4,4))
add(P,"A22->X15","RCPT","Enclosed three-wheeler or small e-van instead of a motorcycle for long routes","NYYY")
add(P,"A22->X15","SRC","Electric motorcycles for the fleet, cutting the rider's own exhaust and the fleet's","NYYY")
add(P,"A22->X15","RCPT","Rider health screening at onboarding and yearly","VYYY",(4,4,3,4,2,2,5,4))
add(P,"A22->X15","DEC","Personal PM monitors on bikes producing an exposure heat map of the city","YYYY",(3,4,3,4,3,3,5,4))
add(P,"A22->X15","DEC","Dispatch algorithm cap on time spent on arterials per shift (the highway ban exists, arterials do not)","VYYY",(3,3,2,4,3,4,4,3))
add(P,"A22->X15","PATH","Delivery hubs closer to demand so each order rides fewer kilometres","NYYY")
add(P,"A25->S18","PATH","Setback rule for new housing from arterials","NNVN")
add(P,"A25->S18","PATH","Noise barriers designed to double as air barriers","NNYY")
add(P,"A25->S18","PATH","Solid barrier plus vegetation at the worst road-facing compounds","NNYY")
add(P,"A25->X18","PATH","Building orientation: bedrooms on the far side from the road in new builds","NNYY")
add(P,"A25->X18","PATH","Non-residential uses (parking, retail) as the roadside buffer","NNYY")
add(P,"A25->S18","SRC","Lower speed limit on the arterial, cutting exhaust and non-exhaust emission","NNVN")
add(P,"A25->S18","SRC","Signal timing that cuts stop-go queues on the stretch","NYVY")
add(P,"D23->X15","DEC","Order batching so each trip carries more","VYYY",(2,4,3,4,4,2,3,4))
add(P,"D23->X15","DEC","Peak-hour delivery surcharge that smooths demand","NYVY")
add(P,"D23->X15","PATH","Pickup lockers that replace door-to-door trips","NYYY")
add(P,"D25->X18","DEC","Zoning: no new schools, nurseries or clinics within 300 m of an arterial","NNVN")
add(P,"D25->X18","RCPT","Retrofit filtration in existing near-road labour housing","VYYY",(5,4,3,4,2,4,5,4))
add(P,"D25->X18","DEC","Air-quality disclosure at lease or sale for road-facing units","NNVN")
add(P,"S09->S01","SRC","SO2 and NOx control at refineries and power plants","NNVN")
add(P,"S17->S01","SRC","Regional dust cooperation","NNNN")
add(P,"S01->X01","SRC","City fleet electrification","NNVN")
add(P,"S18->E03","RCPT","HEPA purifiers in the road-facing bedrooms of one compound as the pilot","YYYY",(5,5,4,5,3,4,5,5))
add(P,"S18->E07","RCPT","Window sealing plus MERV13 on the AC for road-facing units","YYYY",(4,5,4,5,3,4,5,5))
add(P,"S18->X18","RCPT","Bedroom moved to the rear of the flat where the layout allows","YYYY",(3,5,4,3,3,3,4,5))
add(P,"S18->S28","RCPT","Rider positioning: never behind a bus or truck at the light, stop ahead or upwind","YYYY",(3,5,4,3,3,3,4,5))
add(P,"S28->X15","RCPT","Following-distance rule from diesel vehicles in rider training","YYYY",(3,5,4,3,3,2,4,5))
add(P,"S28->X15","RCPT","Waiting position at red lights ahead of the queue where the app allows","YYYY",(3,5,4,3,3,2,4,5))
add(P,"S28->X15","PATH","Fairing or windscreen that deflects the plume, low effect","YYYY",(2,4,3,3,3,1,3,4))
add(P,"X01->E01","DEC","Public air-quality alerts with plain guidance (the MOCCAE gap)","NYYY")
add(P,"X01->E03","RCPT","Clinic-based advice on exposure for respiratory patients","NYYY")
add(P,"X02->E17","SRC","NO2-targeted retrofit of diesel buses and trucks on the corridor","NNVY")
add(P,"X02->E01","DEC","Low-emission zone on the corridor","NNVN")
add(P,"X12->X15","DEC","Rider protections written into platform licensing","NNVY")
add(P,"X12->E01","RCPT","Targeted protection for labour housing next to highways: filtration and sealing first there","VYYY",(5,4,3,4,2,4,5,4))
add(P,"X18->E17","RCPT","Asthma care access for near-road residents through a mobile clinic","NYYY")
add(P,"X18->E03","RCPT","Health screening for the residents of one road-facing compound","YYYY",(4,4,3,4,2,2,5,4))
add(P,"X18->E01","DEC","Near-road resident register for follow-up","NYVY")
add(P,"S18->X18","DEC","Near-road monitoring network with public data","NYYY")
add(P,"D25->X18","DEC","Developer requirement: air-quality assessment for road-facing housing","NNVN")
add(P,"A22->X15","DEC","Platform publishes rider exposure metrics each quarter","NNVY")
add(P,"A25->X18","DEC","Healthy-streets score for each arterial published by the municipality","NNVY")
add(P,"X18->E02","DEC","Insurance incentive for filtered housing","NNVY")
add(P,"S18->X18","DEC","Community low-cost sensors along one arterial run by residents","YYYY",(3,5,4,4,2,2,5,5))
add(P,"D25->X18","DEC","Tenant information sheet on road-facing units","YYYY",(3,5,4,4,2,1,3,5))
add(P,"A25->S18","PATH","Street canyon geometry rules for new streets","NNVN")
add(P,"S18->X18","PATH","Bus lane placed on the side away from housing","NNVY")
add(P,"S18->X18","DEC","Parking policy that removes kerbside stop-go on the residential side","NNVY")
add(P,"S18->X18","DEC","Freight time windows off the residential arterial at night","NNVY")
add(P,"S18->X18","DEC","Idling ban at loading bays on the corridor","NNVY")
add(P,"S18->X18","SRC","Street washing and sweeping to cut resuspended road dust on the corridor","NYVY")
add(P,"S18->X18","SRC","Dust binder on the corridor's unpaved shoulders","NYVY")
add(P,"D23->X15","SRC","Electrification incentives for delivery fleets","NNVY")
add(P,"S28->X15","RCPT","Rider exposure briefing in the onboarding course, in the riders' languages","YYYY",(4,5,4,4,3,2,3,5))
add(P,"A22->X15","RCPT","Rest-stop siting away from the road edge","VYYY",(3,4,3,4,3,2,4,4))
add(P,"X15->E18","RCPT","Spirometry for riders at one company as the pilot cohort","YYYY",(4,4,3,3,2,2,5,4))
add(P,"S28->X15","DEC","Rider app shows the exposure of each route option","VYYY",(3,4,3,4,3,3,4,4))
add(P,"D25->X18","RCPT","Filtered fresh-air unit in the shared rooms of one labour accommodation as the pilot","YYYY",(5,4,3,5,3,4,5,4))
add(P,"X18->E17","RCPT","Asthma screening and inhaler access at one labour accommodation","YYYY",(5,4,3,4,2,2,4,4))
add(P,"S28->X15","PATH","Lane choice guidance: the kerbside lane is the worst behind buses, ride the middle lane where legal","YYYY",(3,5,4,3,3,2,4,5))

WEIGHTS = {"User":1,"Feasibility":2,"Implementability":2,"Usability":1,"Market":1,"Impact":3,"Measurability":2,"Time":1}
COLS = list(WEIGHTS)
